services:
  api:
    image: webdevops/php-apache-dev:8.3-alpine
    container_name: api
    working_dir: /app
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./api:/app
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
    networks:
      - js_learning
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./docker/db/cache:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD:-pass}"
      POSTGRES_USER: "${DB_USER:-js_user}"
    networks:
      - js_learning
  node:
    image: node:latest
    container_name: node
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "${REACT_PORT:-3000}:3000"
    command: sh -c "${REACT_COMMAND:-tail -f /dev/null}"
    networks:
      - js_learning

networks:
  js_learning: