services:
  api:
    image: webdevops/php-apache-dev:8.3-alpine
    container_name: api
    working_dir: /app
    ports:
      - "${API_PORT:-80}:80"
    volumes:
      - ./api:/app
    environment:
      WEB_DOCUMENT_ROOT: "/app/public"
      WEB_DOCUMENT_INDEX: "index.php"
      XDEBUG_MODE: debug
      XDEBUG_START_WITH_REQUEST: yes
      XDEBUG_CLIENT_HOST: host.docker.internal
    networks:
      - js_learning
  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-local_password}
      POSTGRES_USER: ${DB_USER:-app}
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${DB_DATABASE:-app}", "-U", "${DB_USER:-app}" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./docker/db/cache:/var/lib/postgresql/data:rw
    networks:
      - js_learning
  node:
    image: node:latest
    container_name: node
    working_dir: /app
    volumes:
      - ./react:/app
    ports:
      - "${REACT_PORT:-3000}:3000"
    command: sh -c "${REACT_COMMAND:-tail -f /dev/null}"
    networks:
      - js_learning

networks:
  js_learning:
